/* autogenerated by Processing revision 1290 on 2023-03-02 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class DoddleDevelop extends PApplet {

enum direction{
   up,
   down;
}

class Cell{
   boolean isSolid;
   int r;
   int g;
   int b;
   
   public Cell(){
      isSolid = false;
      this.r = 255;
      this.g = 255;
      this.b = 255;
   }
      
   public Cell(int r, int g, int b){
      isSolid = true;
      this.r = r;
      this.g = g;
      this.b = b;
   }
 }

class grid{
   Cell[][] board;
   int doddleY;
   int doddleX;
   int pivt;
   int curstep;
   int maxstep;
   direction dir;
   public grid(int y, int x){
      board = new Cell[y][x];
      
      for (int j = 0; j < y; j++){
         for (int i = 0; i < x; i++){
            if (random(100) > 95) {
               board[j][i] = new Cell((int) random(255), (int) random(255), (int) random(255));
               if (i - 1 >= 0){
                  board[j][i - 1] = new Cell((int) random(255), (int) random(255), (int) random(255));
               }
               
               if (i + 1 < 40){
                  board[j][i + 1] = new Cell((int) random(255), (int) random(255), (int) random(255));
               }
            }else {
               board[j][i] = new Cell();
            }
         }
         
         doddleX = x / 2;
         doddleY = y - 10;
      }
      pivt = y - 40;
      curstep = 0;
      maxstep = 8;
      dir = direction.up;
   }

}

grid testGrid = new grid(160, 40);


public void setup(){
   /* size commented out by preprocessor */;
   noStroke();
}

public void draw(){
   background(255);
   doddleDraw();
 
}

public void doddleDraw(){
   printBoard();
   
   if (testGrid.dir == direction.up){
      if (testGrid.board[testGrid.doddleY - 1][testGrid.doddleX].isSolid){
         testGrid.dir = direction.down;
         return;
      }
      testGrid.doddleY--;
      testGrid.curstep++;
      if (testGrid.curstep == testGrid.maxstep){
         testGrid.dir = direction.down;
      }
   }else if (testGrid.dir == direction.down){
      if (testGrid.doddleY - testGrid.pivt >= 39){
         exit();
      }
      
      println(testGrid.doddleY);
      
      if (testGrid.doddleY + 1 < 160 && testGrid.board[testGrid.doddleY + 1][testGrid.doddleX].isSolid){
        testGrid.dir = direction.up;
        if (testGrid.curstep > 0){
           testGrid.pivt -= testGrid.curstep;
           testGrid.curstep = 0;
        }
        
        return;
      }
      testGrid.doddleY++;
      testGrid.curstep--;
      
   }
   delay(45);
   
    
}


public void printBoard(){
   for (int j = testGrid.pivt; j < testGrid.pivt + 40; j++){
     int mark = testGrid.pivt;
     for (int i = 0; i < 40; i++){
        int optic = 150;
        if (j == testGrid.doddleY && i == testGrid.doddleX){
           fill(0, 0, 0);  
        }else{
           if (!testGrid.board[j][i].isSolid){
              noStroke();
           }else{
              stroke(0);
           }
           
           fill(testGrid.board[j][i].r, testGrid.board[j][i].g, testGrid.board[j][i].b, optic);
           
        }
        rect(i * 10, (j - mark) * 10, 10, 10);
     }  
   }
   
}


public void keyPressed(){
   if (keyCode == LEFT){
      if (testGrid.doddleX - 1 >= 0 && testGrid.board[testGrid.doddleY][testGrid.doddleX - 1].isSolid){
         return;
      }
      testGrid.doddleX--;
      if (testGrid.doddleX == 0){
         testGrid.doddleX = 39;
      }

   }else if (keyCode == RIGHT){
      if (testGrid.doddleX + 1 < 40 && testGrid.board[testGrid.doddleY][testGrid.doddleX + 1].isSolid){
         return;
      }
      testGrid.doddleX++;
      if (testGrid.doddleX == 40){
         testGrid.doddleX = 0;
      }

   }
}


  public void settings() { size(400, 400); }

  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "DoddleDevelop" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
